version: '3.8'

services:
  app:
    image: ikhsan816/society:latest
    container_name: society-app
    ports:
      - "3000:3000"
    networks:
      - society-net

  nginx:
    build: .
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - society-net
    depends_on:
      - certbot

  api:
    image: ikhsan816/society-api:latest
    container_name: society-api
    ports:
      - "3001:3001"
    stdin_open: true
    environment:
      - DATABASE_URL=postgresql://postgres:123456@db:5432/society?schema=public
      - JWT_SECRET_KEY=ThisISMySuppErSecRETasdasd
      - JWT_EXPIRES_IN=1h
      - ENVIRONMENT=production
      - HOST=society.my.id
      - PORT=3001
    depends_on:
      - db
    networks:
      - society-net

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    # command: certonly --webroot -w /var/www/certbot --force-renewal --email ikhsanapriliano4@gmail.com -d society.my.id --agree-tos
    networks:
      - society-net

  db:
    image: postgres:latest
    container_name: society-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - society-net

volumes:
  postgres_data:

networks:
  society-net: