version: '3.8'

services:
  app:
    image: ikhsan816/society:latest
    container_name: society-app
    ports:
      - "3000:3000"
    networks:
      - webnet

  nginx:
    build: .
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - webnet

networks:
  webnet: