version: '3.8'

services:
  api:
    build: .
    container_name: society-api
    ports:
      - "3001:3001"
    stdin_open: true
    environment:
      - DATABASE_URL=postgresql://postgres:123456@db:5432/society?schema=public
      - JWT_SECRET_KEY=ThisISMySuppErSecRETasdasd
      - JWT_EXPIRES_IN=1h
      - ENVIRONMENT=development
      - HOST=localhost
      - PORT=3001
    depends_on:
      - db
    networks:
      - society-network

  db:
    image: postgres:latest
    container_name: society-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - society-network

volumes:
  postgres_data:

networks:
  society-network: