name: Build and Push Docker Images + Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Image Api
      working-directory: api
      run: |
        docker build -t ikhsan816/society-api:latest .
        docker push ikhsan816/society-api:latest

    - name: Build and Push Image Client
      working-directory: client
      run: |
        docker build -t ikhsan816/society:latest .
        docker push ikhsan816/society:latest

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      run: |
        ssh -v -o StrictHostKeyChecking=no root@203.194.114.235 "cd society/client && docker compose down && docker compose pull && docker compose up -d"